// Copyright 2024 Fukuro
// SPDX-License-Identifier: GPL-2.0-or-later

#pragma once
/**/
#define SPI_SCK_PIN GP10
#define SPI_MOSI_PIN GP11
#define SPI_MISO_PIN GP12
#define PMW33XX_CS_PIN  GP0
#define PMW33XX_CPI 900
#define PMW33XX_CLOCK_SPEED 2000000
#define MOUSE_EXTENDED_REPORT
#define POINTING_DEVICE_INVERT_X


#define RGBLIGHT_LAYERS_RETAIN_VAL
#define RGBLIGHT_LAYERS
#define RGBLIGHT_LAYERS_OVERRIDE_RGB_OFF
#define RGBLIGHT_MAX_LAYERS 8
#define RGBLIGHT_DEFAULT_HUE 169
#define RGBLIGHT_LIMIT_VAL 100

#define DYNAMIC_KEYMAP_LAYER_COUNT 6

#define OLED_DC_PIN GP7
#define OLED_CS_PIN GP8
