# Processor frequency
POINTING_DEVICE_ENABLE = yes
POINTING_DEVICE_DRIVER = pmw3360
OLED_ENABLE = yes
OLED_DRIVER = ssd1306
LTO_ENABLE = yes
RGBLIGHT_ENABLE = yes

NO_USB_STARTUP_CHECK = yes
WAIT_FOR_USB = yes


