// Copyright 2024 Fukuro
// SPDX-License-Identifier: GPL-2.0-or-later

#pragma once

#define SPLIT_HAND_MATRIX_GRID GP26, GP5
#define SPLIT_HAND_MATRIX_GRID_LOW_IS_LEFT
#define MATRIX_GRID_PULLDOWN
#define SPLIT_LAYER_STATE_ENABLE



#define SERIAL_USART_FULL_DUPLEX  // フルデュプレックスモード（Tx/Rx別ピン）
#define SERIAL_USART_TX_PIN GP0   // Txピン
#define SERIAL_USART_RX_PIN GP1   // Rxピン
#define SERIAL_USART_DRIVER SD1   // RP2040の場合のドライバID（MCUによる）
#define SERIAL_USART_TX_PAL_MODE 7  // ピンモード（RP2040推奨値）
#define SERIAL_USART_RX_PAL_MODE 7

#define SPI_DRIVER SPID1
#define POINTING_DEVICE_CS_PIN  GP13
#define SPI_SCK_PIN GP10
#define SPI_MISO_PIN GP12
#define SPI_MOSI_PIN GP11
#define SPLIT_POINTING_ENABLE
#define SPLIT_WATCHDOG_ENABLE
#define POINTING_DEVICE_COMBINED


#define PMW33XX_CPI 900
#define PMW33XX_CLOCK_SPEED 2000000
#define ROTATIONAL_TRANSFORM_ANGLE -15
#define POINTING_DEVICE_INVERT_X

#define RGBLIGHT_LAYERS
#define RGBLIGHT_LIMIT_VAL 200
#define RGBLIGHT_MAX_LAYERS 10

