
BOOTMAGIC_ENABLE = yes

CUSTOM_MATRIX = lite
CONSOLE_ENABLE = yes
SRC += matrix.c

POINTING_DEVICE_ENABLE = yes
POINTING_DEVICE_DRIVER = pmw3360
SPLIT_POINTING_ENABLE = yes 
POINTING_DEVICE_COMBINED = yes  

ENCODER_MAP_ENABLE = yes

SERIAL_DRIVER = vendor

RGBLIGHT_ENABLE = yes
RGBLIGHT_DRIVER = ws2812

SPLIT_KEYBOARD = yes

