
VIA_ENABLE = yes
POINTING_DEVICE_ENABLE = yes
POINTING_DEVICE_DRIVER = pmw3360
SPLIT_POINTING_ENABLE = yes 
POINTING_DEVICE_COMBINED = yes  

ENCODER_MAP_ENABLE = yes

SPLIT_KEYBOARD = yes
SERIAL_DRIVER = vendor

RGBLIGHT_ENABLE = yes
RGBLIGHT_DRIVER = ws2812

MIDI_ENABLE = yes
AUDIO_ENABLE = yes



