// Copyright 2024 Fukuro
// SPDX-License-Identifier: GPL-2.0-or-later

#pragma once

#define EEPROM_SIZE 2048
#define WEAR_LEVELING_RP2040_FLASH_SIZE (2 * 1024 * 1024)
#define DYNAMIC_KEYMAP_EEPROM_MAX_ADDR 2047  // (EEPROM_SIZE - 1) を計算して

#define SPLIT_HAND_MATRIX_GRID GP26, GP5
#define SPLIT_HAND_MATRIX_GRID_LOW_IS_LEFT
#define MATRIX_GRID_PULLDOWN
#define SPLIT_LAYER_STATE_ENABLE

#define DEBUG_MATRIX_SCAN_RATE
#define DEBUG_LEVEL 3

#define MATRIX_ROWS 22  // 左11 + 右11
#define MATRIX_COLS 11

#define BOOTMAGIC_LITE_ROW 0      // 左側の行 (row)
#define BOOTMAGIC_LITE_COLUMN 10  // 左側の列 (column)
#define BOOTMAGIC_LITE_ROW_RIGHT 11    // 右側の行 (row)
#define BOOTMAGIC_LITE_COLUMN_RIGHT 0  // 右側の列 (column)

#define SERIAL_USART_FULL_DUPLEX  
#define SERIAL_USART_TX_PIN GP0  
#define SERIAL_USART_RX_PIN GP1   
#define SERIAL_USART_DRIVER SD1   
#define SERIAL_USART_TX_PAL_MODE 7  
#define SERIAL_USART_RX_PAL_MODE 7

#define SPI_DRIVER SPID1
#define POINTING_DEVICE_CS_PIN  GP13
#define SPI_SCK_PIN GP10
#define SPI_MISO_PIN GP12
#define SPI_MOSI_PIN GP11
#define SPLIT_POINTING_ENABLE
#define SPLIT_WATCHDOG_ENABLE
#define POINTING_DEVICE_COMBINED


#define PMW33XX_CPI 900
#define PMW33XX_CLOCK_SPEED 2000000
#define ROTATIONAL_TRANSFORM_ANGLE -15
#define POINTING_DEVICE_INVERT_X

#define RGBLIGHT_LAYERS
#define RGBLIGHT_LIMIT_VAL 200
#define RGBLIGHT_MAX_LAYERS 10

