// Copyright 2024 Fukuro
// SPDX-License-Identifier: GPL-2.0-or-later

#pragma once

#define SPLIT_HAND_MATRIX_GRID GP26, GP5
#define SPLIT_HAND_MATRIX_GRID_LOW_IS_LEFT
#define MATRIX_GRID_PULLDOWN
#define SPLIT_LAYER_STATE_ENABLE

#define DEBUG_MATRIX_SCAN_RATE
#define DEBUG_LEVEL 3

#define MATRIX_ROWS 10  // 左5 + 右5
#define MATRIX_COLS 6

#define BOOTMAGIC_LITE_ROW 0      // 左側の行 (row)
#define BOOTMAGIC_LITE_COLUMN 5  // 左側の列 (column)
#define BOOTMAGIC_LITE_ROW_RIGHT 5    // 右側の行 (row)
#define BOOTMAGIC_LITE_COLUMN_RIGHT 0  // 右側の列 (column)

#define SERIAL_USART_FULL_DUPLEX  
#define SERIAL_USART_TX_PIN GP0  
#define SERIAL_USART_RX_PIN GP1   
#define SERIAL_USART_DRIVER SD1   
#define SERIAL_USART_TX_PAL_MODE 7  
#define SERIAL_USART_RX_PAL_MODE 7

#define SPI_DRIVER SPID1
#define POINTING_DEVICE_CS_PIN  GP13
#define SPI_SCK_PIN GP10
#define SPI_MISO_PIN GP12
#define SPI_MOSI_PIN GP11
#define SPLIT_POINTING_ENABLE
#define SPLIT_WATCHDOG_ENABLE
#define POINTING_DEVICE_COMBINED


#define PMW33XX_CPI 900
#define PMW33XX_CLOCK_SPEED 2000000
#define ROTATIONAL_TRANSFORM_ANGLE -15
#define POINTING_DEVICE_INVERT_X

#define RGBLIGHT_LAYERS
#define RGBLIGHT_LIMIT_VAL 200
#define RGBLIGHT_MAX_LAYERS 10

